apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pet-deploy
  name: choney-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: choney-deploy
  template:
    metadata:
      labels:
        app: choney-deploy
    spec:
      containers:
      - image: clhamo/rabbit:bhutan
        name: pet
